// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optio/lockup/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryActiveLocksRequest is request type for the Query/ActiveLocks RPC method.
type QueryActiveLocksRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryActiveLocksRequest) Reset()         { *m = QueryActiveLocksRequest{} }
func (m *QueryActiveLocksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActiveLocksRequest) ProtoMessage()    {}
func (*QueryActiveLocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{0}
}
func (m *QueryActiveLocksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActiveLocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActiveLocksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActiveLocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActiveLocksRequest.Merge(m, src)
}
func (m *QueryActiveLocksRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActiveLocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActiveLocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActiveLocksRequest proto.InternalMessageInfo

func (m *QueryActiveLocksRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryActiveLocksResponse is response type for the Query/ActiveLocks RPC method.
type QueryActiveLocksResponse struct {
	Locks      []ActiveLock        `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryActiveLocksResponse) Reset()         { *m = QueryActiveLocksResponse{} }
func (m *QueryActiveLocksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryActiveLocksResponse) ProtoMessage()    {}
func (*QueryActiveLocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{1}
}
func (m *QueryActiveLocksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActiveLocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActiveLocksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActiveLocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActiveLocksResponse.Merge(m, src)
}
func (m *QueryActiveLocksResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActiveLocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActiveLocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActiveLocksResponse proto.InternalMessageInfo

func (m *QueryActiveLocksResponse) GetLocks() []ActiveLock {
	if m != nil {
		return m.Locks
	}
	return nil
}

func (m *QueryActiveLocksResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ActiveLock struct {
	Address    string                `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	UnlockDate string                `protobuf:"bytes,2,opt,name=unlock_date,json=unlockDate,proto3" json:"unlock_date,omitempty"`
	Amount     cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *ActiveLock) Reset()         { *m = ActiveLock{} }
func (m *ActiveLock) String() string { return proto.CompactTextString(m) }
func (*ActiveLock) ProtoMessage()    {}
func (*ActiveLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{2}
}
func (m *ActiveLock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveLock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveLock.Merge(m, src)
}
func (m *ActiveLock) XXX_Size() int {
	return m.Size()
}
func (m *ActiveLock) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveLock.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveLock proto.InternalMessageInfo

func (m *ActiveLock) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ActiveLock) GetUnlockDate() string {
	if m != nil {
		return m.UnlockDate
	}
	return ""
}

// QueryTotalLockedAmountRequest is request type for the Query/TotalLockedAmount RPC method.
type QueryTotalLockedAmountRequest struct {
}

func (m *QueryTotalLockedAmountRequest) Reset()         { *m = QueryTotalLockedAmountRequest{} }
func (m *QueryTotalLockedAmountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalLockedAmountRequest) ProtoMessage()    {}
func (*QueryTotalLockedAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{3}
}
func (m *QueryTotalLockedAmountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalLockedAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalLockedAmountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalLockedAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalLockedAmountRequest.Merge(m, src)
}
func (m *QueryTotalLockedAmountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalLockedAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalLockedAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalLockedAmountRequest proto.InternalMessageInfo

// QueryTotalLockedAmountResponse is response type for the Query/TotalLockedAmount RPC method.
type QueryTotalLockedAmountResponse struct {
	TotalLocked cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=total_locked,json=totalLocked,proto3,customtype=cosmossdk.io/math.Int" json:"total_locked"`
}

func (m *QueryTotalLockedAmountResponse) Reset()         { *m = QueryTotalLockedAmountResponse{} }
func (m *QueryTotalLockedAmountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalLockedAmountResponse) ProtoMessage()    {}
func (*QueryTotalLockedAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{4}
}
func (m *QueryTotalLockedAmountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalLockedAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalLockedAmountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalLockedAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalLockedAmountResponse.Merge(m, src)
}
func (m *QueryTotalLockedAmountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalLockedAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalLockedAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalLockedAmountResponse proto.InternalMessageInfo

// QueryAccountLocksRequest is request type for the Query/AccountLocks RPC method.
type QueryAccountLocksRequest struct {
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (m *QueryAccountLocksRequest) Reset()         { *m = QueryAccountLocksRequest{} }
func (m *QueryAccountLocksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAccountLocksRequest) ProtoMessage()    {}
func (*QueryAccountLocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{5}
}
func (m *QueryAccountLocksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountLocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountLocksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountLocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountLocksRequest.Merge(m, src)
}
func (m *QueryAccountLocksRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountLocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountLocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountLocksRequest proto.InternalMessageInfo

func (m *QueryAccountLocksRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// QueryAccountLocksResponse is response type for the Query/AccountLocks RPC method.
type QueryAccountLocksResponse struct {
	Locks []AccountLocks `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks"`
}

func (m *QueryAccountLocksResponse) Reset()         { *m = QueryAccountLocksResponse{} }
func (m *QueryAccountLocksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAccountLocksResponse) ProtoMessage()    {}
func (*QueryAccountLocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{6}
}
func (m *QueryAccountLocksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountLocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountLocksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountLocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountLocksResponse.Merge(m, src)
}
func (m *QueryAccountLocksResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountLocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountLocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountLocksResponse proto.InternalMessageInfo

func (m *QueryAccountLocksResponse) GetLocks() []AccountLocks {
	if m != nil {
		return m.Locks
	}
	return nil
}

type AccountLocks struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Locks   []Lock `protobuf:"bytes,2,rep,name=locks,proto3" json:"locks"`
}

func (m *AccountLocks) Reset()         { *m = AccountLocks{} }
func (m *AccountLocks) String() string { return proto.CompactTextString(m) }
func (*AccountLocks) ProtoMessage()    {}
func (*AccountLocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{7}
}
func (m *AccountLocks) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountLocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountLocks.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountLocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLocks.Merge(m, src)
}
func (m *AccountLocks) XXX_Size() int {
	return m.Size()
}
func (m *AccountLocks) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLocks.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLocks proto.InternalMessageInfo

func (m *AccountLocks) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountLocks) GetLocks() []Lock {
	if m != nil {
		return m.Locks
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryActiveLocksRequest)(nil), "optio.lockup.QueryActiveLocksRequest")
	proto.RegisterType((*QueryActiveLocksResponse)(nil), "optio.lockup.QueryActiveLocksResponse")
	proto.RegisterType((*ActiveLock)(nil), "optio.lockup.ActiveLock")
	proto.RegisterType((*QueryTotalLockedAmountRequest)(nil), "optio.lockup.QueryTotalLockedAmountRequest")
	proto.RegisterType((*QueryTotalLockedAmountResponse)(nil), "optio.lockup.QueryTotalLockedAmountResponse")
	proto.RegisterType((*QueryAccountLocksRequest)(nil), "optio.lockup.QueryAccountLocksRequest")
	proto.RegisterType((*QueryAccountLocksResponse)(nil), "optio.lockup.QueryAccountLocksResponse")
	proto.RegisterType((*AccountLocks)(nil), "optio.lockup.AccountLocks")
}

func init() { proto.RegisterFile("optio/lockup/query.proto", fileDescriptor_4513e58b3df6d044) }

var fileDescriptor_4513e58b3df6d044 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x8d, 0x9b, 0xaf, 0xfd, 0x94, 0x49, 0x36, 0x8c, 0x40, 0x35, 0x26, 0x71, 0x8a, 0x2b, 0xda,
	0x02, 0xd5, 0x8c, 0x1a, 0x7e, 0xc4, 0x92, 0x46, 0xa8, 0x08, 0x09, 0xf1, 0x63, 0x58, 0x20, 0x36,
	0xd1, 0xc4, 0x19, 0xb9, 0x56, 0x12, 0x8f, 0x9b, 0x19, 0x17, 0xba, 0x41, 0x08, 0xf1, 0x00, 0x48,
	0xac, 0xfa, 0x10, 0xbc, 0x47, 0x97, 0x95, 0xd8, 0x20, 0x16, 0x15, 0x4a, 0x78, 0x10, 0x34, 0x3f,
	0xad, 0xe3, 0xfc, 0x10, 0x56, 0x49, 0x7c, 0xce, 0xbd, 0xe7, 0xdc, 0x7b, 0x8f, 0x03, 0x6c, 0x96,
	0x88, 0x88, 0xe1, 0x1e, 0x0b, 0xba, 0x69, 0x82, 0x0f, 0x52, 0x3a, 0x38, 0x42, 0xc9, 0x80, 0x09,
	0x06, 0x2b, 0x0a, 0x41, 0x1a, 0x71, 0x2e, 0x87, 0x2c, 0x64, 0x0a, 0xc0, 0xf2, 0x9b, 0xe6, 0x38,
	0xd5, 0x90, 0xb1, 0xb0, 0x47, 0x31, 0x49, 0x22, 0x4c, 0xe2, 0x98, 0x09, 0x22, 0x22, 0x16, 0x73,
	0x83, 0xde, 0x0a, 0x18, 0xef, 0x33, 0x8e, 0xdb, 0x84, 0x53, 0xdd, 0x1a, 0x1f, 0xee, 0xb4, 0xa9,
	0x20, 0x3b, 0x38, 0x21, 0x61, 0x14, 0x2b, 0xb2, 0xe1, 0xae, 0xe6, 0x7c, 0xc8, 0x0f, 0x0d, 0x78,
	0x04, 0xac, 0xbe, 0x94, 0xa5, 0xbb, 0x81, 0x88, 0x0e, 0xe9, 0x53, 0x16, 0x74, 0xb9, 0x4f, 0x0f,
	0x52, 0xca, 0x05, 0xdc, 0x03, 0x20, 0xeb, 0x63, 0x5b, 0x6b, 0xd6, 0x56, 0xb9, 0xb1, 0x81, 0xb4,
	0x28, 0x92, 0xa2, 0x48, 0xcf, 0x63, 0x44, 0xd1, 0x0b, 0x12, 0x52, 0x53, 0xeb, 0x8f, 0x55, 0x7a,
	0xc7, 0x16, 0xb0, 0xa7, 0x35, 0x78, 0xc2, 0x62, 0x4e, 0xe1, 0x5d, 0xb0, 0x2c, 0xdd, 0x70, 0xdb,
	0x5a, 0x2b, 0x6e, 0x95, 0x1b, 0x36, 0x1a, 0x5f, 0x0b, 0xca, 0x2a, 0x9a, 0xff, 0x9d, 0x9c, 0xd5,
	0x0b, 0xbe, 0x26, 0xc3, 0xc7, 0x39, 0x6b, 0x4b, 0xca, 0xda, 0xe6, 0x42, 0x6b, 0x5a, 0x32, 0xe7,
	0xed, 0x03, 0x00, 0x99, 0x06, 0xb4, 0xc1, 0xff, 0xa4, 0xd3, 0x19, 0x50, 0xce, 0xd5, 0xb8, 0x25,
	0xff, 0xfc, 0x27, 0xac, 0x83, 0x72, 0x1a, 0x4b, 0xed, 0x56, 0x87, 0x08, 0xaa, 0x14, 0x4b, 0x3e,
	0xd0, 0x8f, 0x1e, 0x11, 0x41, 0xe1, 0x3d, 0xb0, 0x42, 0xfa, 0x2c, 0x8d, 0x85, 0x5d, 0x94, 0x58,
	0xb3, 0x26, 0xed, 0xfe, 0x3c, 0xab, 0x5f, 0xd1, 0xa6, 0x78, 0xa7, 0x8b, 0x22, 0x86, 0xfb, 0x44,
	0xec, 0xa3, 0x27, 0xb1, 0xf0, 0x0d, 0xd9, 0xab, 0x83, 0x9a, 0x5a, 0xcd, 0x6b, 0x26, 0x48, 0x4f,
	0x7a, 0xa0, 0x9d, 0x5d, 0x85, 0x98, 0x45, 0x7a, 0x6d, 0xe0, 0xce, 0x23, 0x98, 0x0d, 0x3e, 0x04,
	0x15, 0x21, 0xc1, 0x56, 0x4f, 0xa1, 0xda, 0xf9, 0x22, 0xfd, 0xb2, 0xc8, 0xfa, 0x79, 0x0f, 0x2e,
	0xee, 0x13, 0xc8, 0xce, 0xb9, 0x10, 0x54, 0x41, 0xc9, 0xec, 0x80, 0xea, 0x1b, 0x95, 0xfc, 0xec,
	0x81, 0xf7, 0x0a, 0x5c, 0x9d, 0x51, 0x69, 0x8c, 0xdd, 0xcf, 0x9f, 0xd6, 0x99, 0x3c, 0x6d, 0x56,
	0x92, 0x3b, 0xae, 0xf7, 0x06, 0x54, 0xc6, 0xc1, 0xbf, 0x5c, 0x05, 0x9d, 0x2b, 0x2c, 0x29, 0x05,
	0x98, 0x57, 0x98, 0x8a, 0x4d, 0xe3, 0x5b, 0x11, 0x2c, 0x2b, 0xbf, 0xf0, 0xa3, 0x05, 0xca, 0x63,
	0x71, 0x84, 0x37, 0xf2, 0xa5, 0x73, 0x5e, 0x09, 0x67, 0x63, 0x11, 0x4d, 0x8f, 0xee, 0x79, 0x9f,
	0xbe, 0xff, 0xfe, 0xba, 0x54, 0x85, 0x0e, 0xce, 0xbd, 0x77, 0x44, 0x51, 0x5b, 0x3a, 0xc3, 0xc7,
	0x16, 0xb8, 0x34, 0x75, 0x55, 0x78, 0x7b, 0x86, 0xc2, 0xbc, 0x70, 0x38, 0xdb, 0xff, 0x46, 0x36,
	0xa6, 0x6e, 0x2a, 0x53, 0xeb, 0xf0, 0x7a, 0xde, 0xd4, 0x78, 0x78, 0x5a, 0x3a, 0x96, 0xf0, 0xb3,
	0x35, 0x71, 0x83, 0xd9, 0x83, 0x4f, 0xc5, 0xc5, 0xd9, 0x5c, 0xc8, 0x33, 0x66, 0xd6, 0x95, 0x99,
	0x1a, 0xbc, 0x36, 0xb9, 0x21, 0xc5, 0xd5, 0x2b, 0x6a, 0xee, 0x9d, 0x0c, 0x5d, 0xeb, 0x74, 0xe8,
	0x5a, 0xbf, 0x86, 0xae, 0xf5, 0x65, 0xe4, 0x16, 0x4e, 0x47, 0x6e, 0xe1, 0xc7, 0xc8, 0x2d, 0xbc,
	0xdd, 0x0e, 0x23, 0xb1, 0x9f, 0xb6, 0x51, 0xc0, 0xfa, 0xf8, 0xb9, 0x6c, 0xf0, 0x8c, 0x8a, 0x77,
	0x6c, 0xd0, 0x35, 0xdd, 0xde, 0x5f, 0x0c, 0x77, 0x94, 0x50, 0xde, 0x5e, 0x51, 0xff, 0x75, 0x77,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x29, 0xf0, 0xc6, 0xe8, 0x8e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ActiveLocks queries all active locks with an unlock time in the future.
	ActiveLocks(ctx context.Context, in *QueryActiveLocksRequest, opts ...grpc.CallOption) (*QueryActiveLocksResponse, error)
	// TotalLockedAmount queries the total amount of tokens locked across all accounts.
	TotalLockedAmount(ctx context.Context, in *QueryTotalLockedAmountRequest, opts ...grpc.CallOption) (*QueryTotalLockedAmountResponse, error)
	// AccountLocks queries active locks for multiple accounts.
	AccountLocks(ctx context.Context, in *QueryAccountLocksRequest, opts ...grpc.CallOption) (*QueryAccountLocksResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ActiveLocks(ctx context.Context, in *QueryActiveLocksRequest, opts ...grpc.CallOption) (*QueryActiveLocksResponse, error) {
	out := new(QueryActiveLocksResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Query/ActiveLocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TotalLockedAmount(ctx context.Context, in *QueryTotalLockedAmountRequest, opts ...grpc.CallOption) (*QueryTotalLockedAmountResponse, error) {
	out := new(QueryTotalLockedAmountResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Query/TotalLockedAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AccountLocks(ctx context.Context, in *QueryAccountLocksRequest, opts ...grpc.CallOption) (*QueryAccountLocksResponse, error) {
	out := new(QueryAccountLocksResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Query/AccountLocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ActiveLocks queries all active locks with an unlock time in the future.
	ActiveLocks(context.Context, *QueryActiveLocksRequest) (*QueryActiveLocksResponse, error)
	// TotalLockedAmount queries the total amount of tokens locked across all accounts.
	TotalLockedAmount(context.Context, *QueryTotalLockedAmountRequest) (*QueryTotalLockedAmountResponse, error)
	// AccountLocks queries active locks for multiple accounts.
	AccountLocks(context.Context, *QueryAccountLocksRequest) (*QueryAccountLocksResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ActiveLocks(ctx context.Context, req *QueryActiveLocksRequest) (*QueryActiveLocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveLocks not implemented")
}
func (*UnimplementedQueryServer) TotalLockedAmount(ctx context.Context, req *QueryTotalLockedAmountRequest) (*QueryTotalLockedAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalLockedAmount not implemented")
}
func (*UnimplementedQueryServer) AccountLocks(ctx context.Context, req *QueryAccountLocksRequest) (*QueryAccountLocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountLocks not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ActiveLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActiveLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActiveLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Query/ActiveLocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActiveLocks(ctx, req.(*QueryActiveLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TotalLockedAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalLockedAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TotalLockedAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Query/TotalLockedAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TotalLockedAmount(ctx, req.(*QueryTotalLockedAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AccountLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AccountLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Query/AccountLocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AccountLocks(ctx, req.(*QueryAccountLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "optio.lockup.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActiveLocks",
			Handler:    _Query_ActiveLocks_Handler,
		},
		{
			MethodName: "TotalLockedAmount",
			Handler:    _Query_TotalLockedAmount_Handler,
		},
		{
			MethodName: "AccountLocks",
			Handler:    _Query_AccountLocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optio/lockup/query.proto",
}

func (m *QueryActiveLocksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActiveLocksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActiveLocksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryActiveLocksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActiveLocksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActiveLocksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ActiveLock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveLock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveLock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.UnlockDate) > 0 {
		i -= len(m.UnlockDate)
		copy(dAtA[i:], m.UnlockDate)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UnlockDate)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTotalLockedAmountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalLockedAmountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalLockedAmountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTotalLockedAmountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalLockedAmountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalLockedAmountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalLocked.Size()
		i -= size
		if _, err := m.TotalLocked.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAccountLocksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountLocksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountLocksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAccountLocksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountLocksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountLocksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AccountLocks) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountLocks) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountLocks) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryActiveLocksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryActiveLocksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *ActiveLock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.UnlockDate)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTotalLockedAmountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTotalLockedAmountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalLocked.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAccountLocksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryAccountLocksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *AccountLocks) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryActiveLocksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActiveLocksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActiveLocksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActiveLocksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActiveLocksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActiveLocksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, ActiveLock{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActiveLock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveLock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveLock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnlockDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalLockedAmountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalLockedAmountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalLockedAmountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalLockedAmountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalLockedAmountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalLockedAmountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLocked", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalLocked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountLocksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountLocksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountLocksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountLocksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountLocksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountLocksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, AccountLocks{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountLocks) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountLocks: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountLocks: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, Lock{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
