// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optio/lockup/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryActiveLocksRequest is request type for the Query/ActiveLocks RPC method.
type QueryActiveLocksRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryActiveLocksRequest) Reset()         { *m = QueryActiveLocksRequest{} }
func (m *QueryActiveLocksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActiveLocksRequest) ProtoMessage()    {}
func (*QueryActiveLocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{0}
}
func (m *QueryActiveLocksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActiveLocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActiveLocksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActiveLocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActiveLocksRequest.Merge(m, src)
}
func (m *QueryActiveLocksRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActiveLocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActiveLocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActiveLocksRequest proto.InternalMessageInfo

func (m *QueryActiveLocksRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryActiveLocksResponse is response type for the Query/ActiveLocks RPC method.
type QueryActiveLocksResponse struct {
	Locks      []ActiveLockResource `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks"`
	Pagination *query.PageResponse  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryActiveLocksResponse) Reset()         { *m = QueryActiveLocksResponse{} }
func (m *QueryActiveLocksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryActiveLocksResponse) ProtoMessage()    {}
func (*QueryActiveLocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{1}
}
func (m *QueryActiveLocksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActiveLocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActiveLocksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActiveLocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActiveLocksResponse.Merge(m, src)
}
func (m *QueryActiveLocksResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActiveLocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActiveLocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActiveLocksResponse proto.InternalMessageInfo

func (m *QueryActiveLocksResponse) GetLocks() []ActiveLockResource {
	if m != nil {
		return m.Locks
	}
	return nil
}

func (m *QueryActiveLocksResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ActiveLockResource struct {
	Address    string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	UnlockDate string     `protobuf:"bytes,2,opt,name=unlock_date,json=unlockDate,proto3" json:"unlock_date,omitempty"`
	Amount     types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
}

func (m *ActiveLockResource) Reset()         { *m = ActiveLockResource{} }
func (m *ActiveLockResource) String() string { return proto.CompactTextString(m) }
func (*ActiveLockResource) ProtoMessage()    {}
func (*ActiveLockResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{2}
}
func (m *ActiveLockResource) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveLockResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveLockResource.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveLockResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveLockResource.Merge(m, src)
}
func (m *ActiveLockResource) XXX_Size() int {
	return m.Size()
}
func (m *ActiveLockResource) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveLockResource.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveLockResource proto.InternalMessageInfo

func (m *ActiveLockResource) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ActiveLockResource) GetUnlockDate() string {
	if m != nil {
		return m.UnlockDate
	}
	return ""
}

func (m *ActiveLockResource) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// QueryTotalLockedAmountRequest is request type for the Query/TotalLockedAmount RPC method.
type QueryTotalLockedAmountRequest struct {
}

func (m *QueryTotalLockedAmountRequest) Reset()         { *m = QueryTotalLockedAmountRequest{} }
func (m *QueryTotalLockedAmountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalLockedAmountRequest) ProtoMessage()    {}
func (*QueryTotalLockedAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{3}
}
func (m *QueryTotalLockedAmountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalLockedAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalLockedAmountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalLockedAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalLockedAmountRequest.Merge(m, src)
}
func (m *QueryTotalLockedAmountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalLockedAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalLockedAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalLockedAmountRequest proto.InternalMessageInfo

// QueryTotalLockedAmountResponse is response type for the Query/TotalLockedAmount RPC method.
type QueryTotalLockedAmountResponse struct {
	TotalLocked types.Coin `protobuf:"bytes,1,opt,name=total_locked,json=totalLocked,proto3" json:"total_locked"`
}

func (m *QueryTotalLockedAmountResponse) Reset()         { *m = QueryTotalLockedAmountResponse{} }
func (m *QueryTotalLockedAmountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalLockedAmountResponse) ProtoMessage()    {}
func (*QueryTotalLockedAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{4}
}
func (m *QueryTotalLockedAmountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalLockedAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalLockedAmountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalLockedAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalLockedAmountResponse.Merge(m, src)
}
func (m *QueryTotalLockedAmountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalLockedAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalLockedAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalLockedAmountResponse proto.InternalMessageInfo

func (m *QueryTotalLockedAmountResponse) GetTotalLocked() types.Coin {
	if m != nil {
		return m.TotalLocked
	}
	return types.Coin{}
}

// QueryLocksForAddressesRequest is request type for the Query/LocksForAddresses RPC method.
type QueryLocksForAddressesRequest struct {
	Addresses  string             `protobuf:"bytes,1,opt,name=addresses,proto3" json:"addresses,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLocksForAddressesRequest) Reset()         { *m = QueryLocksForAddressesRequest{} }
func (m *QueryLocksForAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLocksForAddressesRequest) ProtoMessage()    {}
func (*QueryLocksForAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{5}
}
func (m *QueryLocksForAddressesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLocksForAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLocksForAddressesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLocksForAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLocksForAddressesRequest.Merge(m, src)
}
func (m *QueryLocksForAddressesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLocksForAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLocksForAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLocksForAddressesRequest proto.InternalMessageInfo

func (m *QueryLocksForAddressesRequest) GetAddresses() string {
	if m != nil {
		return m.Addresses
	}
	return ""
}

func (m *QueryLocksForAddressesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLocksForAddressesResponse is response type for the Query/LocksForAddresses RPC method.
type QueryLocksForAddressesResponse struct {
	Locks      []AccountLocksResource `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks"`
	Pagination *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLocksForAddressesResponse) Reset()         { *m = QueryLocksForAddressesResponse{} }
func (m *QueryLocksForAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLocksForAddressesResponse) ProtoMessage()    {}
func (*QueryLocksForAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{6}
}
func (m *QueryLocksForAddressesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLocksForAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLocksForAddressesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLocksForAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLocksForAddressesResponse.Merge(m, src)
}
func (m *QueryLocksForAddressesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLocksForAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLocksForAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLocksForAddressesResponse proto.InternalMessageInfo

func (m *QueryLocksForAddressesResponse) GetLocks() []AccountLocksResource {
	if m != nil {
		return m.Locks
	}
	return nil
}

func (m *QueryLocksForAddressesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type AccountLocksResource struct {
	Address string         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Locks   []LockResource `protobuf:"bytes,2,rep,name=locks,proto3" json:"locks"`
}

func (m *AccountLocksResource) Reset()         { *m = AccountLocksResource{} }
func (m *AccountLocksResource) String() string { return proto.CompactTextString(m) }
func (*AccountLocksResource) ProtoMessage()    {}
func (*AccountLocksResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{7}
}
func (m *AccountLocksResource) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountLocksResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountLocksResource.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountLocksResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLocksResource.Merge(m, src)
}
func (m *AccountLocksResource) XXX_Size() int {
	return m.Size()
}
func (m *AccountLocksResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLocksResource.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLocksResource proto.InternalMessageInfo

func (m *AccountLocksResource) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountLocksResource) GetLocks() []LockResource {
	if m != nil {
		return m.Locks
	}
	return nil
}

type LockResource struct {
	UnlockDate string     `protobuf:"bytes,1,opt,name=unlock_date,json=unlockDate,proto3" json:"unlock_date,omitempty"`
	Amount     types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
}

func (m *LockResource) Reset()         { *m = LockResource{} }
func (m *LockResource) String() string { return proto.CompactTextString(m) }
func (*LockResource) ProtoMessage()    {}
func (*LockResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{8}
}
func (m *LockResource) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LockResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LockResource.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LockResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockResource.Merge(m, src)
}
func (m *LockResource) XXX_Size() int {
	return m.Size()
}
func (m *LockResource) XXX_DiscardUnknown() {
	xxx_messageInfo_LockResource.DiscardUnknown(m)
}

var xxx_messageInfo_LockResource proto.InternalMessageInfo

func (m *LockResource) GetUnlockDate() string {
	if m != nil {
		return m.UnlockDate
	}
	return ""
}

func (m *LockResource) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// QueryLocksRequest is request type for the Query/Locks RPC method.
type QueryLocksRequest struct {
	Address    string             `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLocksRequest) Reset()         { *m = QueryLocksRequest{} }
func (m *QueryLocksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLocksRequest) ProtoMessage()    {}
func (*QueryLocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{9}
}
func (m *QueryLocksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLocksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLocksRequest.Merge(m, src)
}
func (m *QueryLocksRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLocksRequest proto.InternalMessageInfo

func (m *QueryLocksRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryLocksRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLocksResponse is response type for the Query/Locks RPC method.
type QueryLocksResponse struct {
	Locks      []LockResource      `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLocksResponse) Reset()         { *m = QueryLocksResponse{} }
func (m *QueryLocksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLocksResponse) ProtoMessage()    {}
func (*QueryLocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513e58b3df6d044, []int{10}
}
func (m *QueryLocksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLocksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLocksResponse.Merge(m, src)
}
func (m *QueryLocksResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLocksResponse proto.InternalMessageInfo

func (m *QueryLocksResponse) GetLocks() []LockResource {
	if m != nil {
		return m.Locks
	}
	return nil
}

func (m *QueryLocksResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryActiveLocksRequest)(nil), "optio.lockup.QueryActiveLocksRequest")
	proto.RegisterType((*QueryActiveLocksResponse)(nil), "optio.lockup.QueryActiveLocksResponse")
	proto.RegisterType((*ActiveLockResource)(nil), "optio.lockup.ActiveLockResource")
	proto.RegisterType((*QueryTotalLockedAmountRequest)(nil), "optio.lockup.QueryTotalLockedAmountRequest")
	proto.RegisterType((*QueryTotalLockedAmountResponse)(nil), "optio.lockup.QueryTotalLockedAmountResponse")
	proto.RegisterType((*QueryLocksForAddressesRequest)(nil), "optio.lockup.QueryLocksForAddressesRequest")
	proto.RegisterType((*QueryLocksForAddressesResponse)(nil), "optio.lockup.QueryLocksForAddressesResponse")
	proto.RegisterType((*AccountLocksResource)(nil), "optio.lockup.AccountLocksResource")
	proto.RegisterType((*LockResource)(nil), "optio.lockup.LockResource")
	proto.RegisterType((*QueryLocksRequest)(nil), "optio.lockup.QueryLocksRequest")
	proto.RegisterType((*QueryLocksResponse)(nil), "optio.lockup.QueryLocksResponse")
}

func init() { proto.RegisterFile("optio/lockup/query.proto", fileDescriptor_4513e58b3df6d044) }

var fileDescriptor_4513e58b3df6d044 = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0xe9, 0x0f, 0xe9, 0x4b, 0x2f, 0x1d, 0x0a, 0x8d, 0xb1, 0xdd, 0xc4, 0x2d, 0xfd,
	0xa1, 0xd6, 0x5d, 0x5a, 0xa1, 0x5e, 0x44, 0x68, 0x95, 0x7a, 0x11, 0x7f, 0x2c, 0x9e, 0xbc, 0x84,
	0xc9, 0x66, 0xd8, 0x2e, 0x4d, 0x77, 0xb6, 0x3b, 0xb3, 0xd5, 0x22, 0x82, 0x08, 0x82, 0x47, 0xa1,
	0x78, 0xf0, 0xe8, 0xd1, 0xbf, 0xc0, 0x7f, 0xa1, 0xc7, 0x82, 0x17, 0x4f, 0x22, 0xad, 0x7f, 0x88,
	0xec, 0xcc, 0x6c, 0xb3, 0x9b, 0x64, 0xdb, 0x22, 0xf1, 0x94, 0x64, 0xdf, 0x9b, 0xf9, 0x7e, 0xde,
	0x7b, 0xdf, 0x7d, 0x81, 0x2a, 0x0b, 0x85, 0xcf, 0xec, 0x0e, 0x73, 0x77, 0xe2, 0xd0, 0xde, 0x8b,
	0x69, 0x74, 0x60, 0x85, 0x11, 0x13, 0x0c, 0x4f, 0xca, 0x88, 0xa5, 0x22, 0xb5, 0x69, 0x8f, 0x79,
	0x4c, 0x06, 0xec, 0xe4, 0x9b, 0xca, 0xa9, 0xcd, 0x7a, 0x8c, 0x79, 0x1d, 0x6a, 0x93, 0xd0, 0xb7,
	0x49, 0x10, 0x30, 0x41, 0x84, 0xcf, 0x02, 0xae, 0xa3, 0x37, 0x5d, 0xc6, 0x77, 0x19, 0xb7, 0x5b,
	0x84, 0x53, 0x75, 0xb5, 0xbd, 0xbf, 0xda, 0xa2, 0x82, 0xac, 0xda, 0x21, 0xf1, 0xfc, 0x40, 0x26,
	0xeb, 0x5c, 0x23, 0x9b, 0x9b, 0x66, 0xb9, 0xcc, 0x4f, 0xe3, 0x33, 0x39, 0xce, 0xe4, 0x43, 0x05,
	0x4c, 0x02, 0x33, 0xcf, 0x93, 0xab, 0x37, 0x5c, 0xe1, 0xef, 0xd3, 0xc7, 0xcc, 0xdd, 0xe1, 0x0e,
	0xdd, 0x8b, 0x29, 0x17, 0x78, 0x0b, 0xa0, 0xab, 0x53, 0x45, 0x0d, 0xb4, 0x5c, 0x59, 0x5b, 0xb4,
	0x94, 0x90, 0x95, 0x08, 0x59, 0xaa, 0x5e, 0x2d, 0x67, 0x3d, 0x23, 0x1e, 0xd5, 0x67, 0x9d, 0xcc,
	0x49, 0xf3, 0x2b, 0x82, 0x6a, 0xbf, 0x06, 0x0f, 0x59, 0xc0, 0x29, 0xbe, 0x07, 0x63, 0x09, 0x0d,
	0xaf, 0xa2, 0xc6, 0xc8, 0x72, 0x65, 0xad, 0x61, 0x65, 0xdb, 0x66, 0x75, 0x4f, 0x38, 0x94, 0xb3,
	0x38, 0x72, 0xe9, 0xe6, 0xe8, 0xd1, 0xaf, 0x7a, 0xc9, 0x51, 0x87, 0xf0, 0xa3, 0x1c, 0x62, 0x59,
	0x22, 0x2e, 0x5d, 0x88, 0xa8, 0xa4, 0x73, 0x8c, 0x1f, 0x11, 0xe0, 0x7e, 0x31, 0x5c, 0x85, 0x2b,
	0xa4, 0xdd, 0x8e, 0x28, 0xe7, 0xb2, 0xfe, 0x09, 0x27, 0xfd, 0x89, 0xeb, 0x50, 0x89, 0x83, 0x04,
	0xa2, 0xd9, 0x26, 0x82, 0x4a, 0xe9, 0x09, 0x07, 0xd4, 0xa3, 0x87, 0x44, 0x50, 0x7c, 0x17, 0xc6,
	0xc9, 0x2e, 0x8b, 0x03, 0x51, 0x1d, 0x91, 0x58, 0x57, 0x73, 0x58, 0x29, 0xd0, 0x03, 0xe6, 0x07,
	0xba, 0x24, 0x9d, 0x6e, 0xd6, 0x61, 0x4e, 0x76, 0xeb, 0x05, 0x13, 0xa4, 0x93, 0xd0, 0xd0, 0xf6,
	0x86, 0x8c, 0xe8, 0xde, 0x9a, 0x6d, 0x30, 0x8a, 0x12, 0x74, 0x53, 0x37, 0x61, 0x52, 0x24, 0xc1,
	0x66, 0x47, 0x46, 0xf5, 0xec, 0x2e, 0x24, 0xa8, 0x88, 0xee, 0x8d, 0xe6, 0x07, 0xa4, 0x39, 0xe4,
	0xbc, 0xb6, 0x58, 0xb4, 0xa1, 0x2a, 0xa7, 0x67, 0xfe, 0x98, 0x85, 0x09, 0x92, 0x3e, 0xd3, 0xed,
	0xe9, 0x3e, 0xe8, 0x71, 0x4f, 0xf9, 0x9f, 0xdd, 0xf3, 0x0d, 0xe9, 0x72, 0x07, 0x70, 0xe8, 0x72,
	0xef, 0xe7, 0x3d, 0x64, 0xf6, 0x7a, 0xc8, 0x4d, 0x9a, 0x93, 0xda, 0xee, 0x7f, 0xba, 0x68, 0x1b,
	0xa6, 0x07, 0xa9, 0x9d, 0x63, 0xa3, 0xf5, 0x14, 0xbd, 0x2c, 0xd1, 0x6b, 0x79, 0xf4, 0x42, 0xe3,
	0x9b, 0xdb, 0x30, 0x99, 0x33, 0x6a, 0x8f, 0x1d, 0xd1, 0xf0, 0xec, 0x18, 0xc3, 0x54, 0xb7, 0xfd,
	0xe9, 0xe8, 0x8b, 0x0b, 0x1a, 0xd6, 0xd8, 0x3f, 0x23, 0xc0, 0x59, 0x5d, 0x3d, 0xea, 0xf5, 0xfc,
	0xa8, 0x2f, 0xdb, 0xaf, 0xa1, 0x8d, 0x78, 0xed, 0xfb, 0x28, 0x8c, 0x49, 0x2e, 0xfc, 0x0e, 0x41,
	0x25, 0xb3, 0xd1, 0xf0, 0x42, 0x9e, 0xa5, 0x60, 0xab, 0xd6, 0x16, 0x2f, 0x4a, 0x53, 0xa2, 0xa6,
	0xf9, 0xfe, 0xc7, 0x9f, 0xc3, 0xf2, 0x2c, 0xae, 0xd9, 0xb9, 0xd5, 0x4d, 0x64, 0x6a, 0x53, 0x55,
	0xf5, 0x05, 0xc1, 0x54, 0xdf, 0x16, 0xc0, 0xb7, 0x06, 0x28, 0x14, 0x2d, 0x93, 0xda, 0xca, 0xe5,
	0x92, 0x35, 0xd4, 0x0d, 0x09, 0x35, 0x8f, 0xaf, 0xe7, 0xa1, 0xb2, 0xcb, 0xa6, 0xa9, 0x7c, 0x83,
	0x0f, 0x11, 0x4c, 0xf5, 0xbd, 0xb2, 0x03, 0xd9, 0x8a, 0x16, 0xcc, 0x40, 0xb6, 0xc2, 0x2d, 0x60,
	0xce, 0x4b, 0xb6, 0x39, 0x7c, 0xad, 0xb7, 0x61, 0xf2, 0x85, 0xd4, 0x1d, 0x3b, 0x80, 0x31, 0x35,
	0xad, 0x7a, 0xd1, 0xdd, 0xa9, 0x78, 0xa3, 0x38, 0x41, 0x0b, 0xde, 0x96, 0x82, 0x4b, 0x78, 0xe1,
	0x1c, 0x41, 0xfb, 0x8d, 0x7e, 0x31, 0xde, 0x6e, 0x6e, 0x1d, 0x9d, 0x18, 0xe8, 0xf8, 0xc4, 0x40,
	0xbf, 0x4f, 0x0c, 0xf4, 0xe9, 0xd4, 0x28, 0x1d, 0x9f, 0x1a, 0xa5, 0x9f, 0xa7, 0x46, 0xe9, 0xe5,
	0x8a, 0xe7, 0x8b, 0xed, 0xb8, 0x65, 0xb9, 0x6c, 0xd7, 0x7e, 0x9a, 0x5c, 0xf5, 0x84, 0x8a, 0x57,
	0x2c, 0xda, 0xd1, 0xf7, 0xbe, 0x3e, 0x6b, 0xf3, 0x41, 0x48, 0x79, 0x6b, 0x5c, 0xfe, 0x71, 0xdf,
	0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x39, 0x58, 0x4e, 0x7b, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ActiveLocks queries all active locks with an unlock date in the future.
	ActiveLocks(ctx context.Context, in *QueryActiveLocksRequest, opts ...grpc.CallOption) (*QueryActiveLocksResponse, error)
	// TotalLockedAmount queries the total amount of tokens locked across all accounts.
	TotalLockedAmount(ctx context.Context, in *QueryTotalLockedAmountRequest, opts ...grpc.CallOption) (*QueryTotalLockedAmountResponse, error)
	// LocksForAddresses queries active locks for multiple addresses.
	LocksForAddresses(ctx context.Context, in *QueryLocksForAddressesRequest, opts ...grpc.CallOption) (*QueryLocksForAddressesResponse, error)
	// Locks queries active locks for an address.
	Locks(ctx context.Context, in *QueryLocksRequest, opts ...grpc.CallOption) (*QueryLocksResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ActiveLocks(ctx context.Context, in *QueryActiveLocksRequest, opts ...grpc.CallOption) (*QueryActiveLocksResponse, error) {
	out := new(QueryActiveLocksResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Query/ActiveLocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TotalLockedAmount(ctx context.Context, in *QueryTotalLockedAmountRequest, opts ...grpc.CallOption) (*QueryTotalLockedAmountResponse, error) {
	out := new(QueryTotalLockedAmountResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Query/TotalLockedAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LocksForAddresses(ctx context.Context, in *QueryLocksForAddressesRequest, opts ...grpc.CallOption) (*QueryLocksForAddressesResponse, error) {
	out := new(QueryLocksForAddressesResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Query/LocksForAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Locks(ctx context.Context, in *QueryLocksRequest, opts ...grpc.CallOption) (*QueryLocksResponse, error) {
	out := new(QueryLocksResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Query/Locks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ActiveLocks queries all active locks with an unlock date in the future.
	ActiveLocks(context.Context, *QueryActiveLocksRequest) (*QueryActiveLocksResponse, error)
	// TotalLockedAmount queries the total amount of tokens locked across all accounts.
	TotalLockedAmount(context.Context, *QueryTotalLockedAmountRequest) (*QueryTotalLockedAmountResponse, error)
	// LocksForAddresses queries active locks for multiple addresses.
	LocksForAddresses(context.Context, *QueryLocksForAddressesRequest) (*QueryLocksForAddressesResponse, error)
	// Locks queries active locks for an address.
	Locks(context.Context, *QueryLocksRequest) (*QueryLocksResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ActiveLocks(ctx context.Context, req *QueryActiveLocksRequest) (*QueryActiveLocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveLocks not implemented")
}
func (*UnimplementedQueryServer) TotalLockedAmount(ctx context.Context, req *QueryTotalLockedAmountRequest) (*QueryTotalLockedAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalLockedAmount not implemented")
}
func (*UnimplementedQueryServer) LocksForAddresses(ctx context.Context, req *QueryLocksForAddressesRequest) (*QueryLocksForAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocksForAddresses not implemented")
}
func (*UnimplementedQueryServer) Locks(ctx context.Context, req *QueryLocksRequest) (*QueryLocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Locks not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ActiveLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActiveLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActiveLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Query/ActiveLocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActiveLocks(ctx, req.(*QueryActiveLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TotalLockedAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalLockedAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TotalLockedAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Query/TotalLockedAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TotalLockedAmount(ctx, req.(*QueryTotalLockedAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LocksForAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLocksForAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LocksForAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Query/LocksForAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LocksForAddresses(ctx, req.(*QueryLocksForAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Locks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Locks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Query/Locks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Locks(ctx, req.(*QueryLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "optio.lockup.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActiveLocks",
			Handler:    _Query_ActiveLocks_Handler,
		},
		{
			MethodName: "TotalLockedAmount",
			Handler:    _Query_TotalLockedAmount_Handler,
		},
		{
			MethodName: "LocksForAddresses",
			Handler:    _Query_LocksForAddresses_Handler,
		},
		{
			MethodName: "Locks",
			Handler:    _Query_Locks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optio/lockup/query.proto",
}

func (m *QueryActiveLocksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActiveLocksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActiveLocksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryActiveLocksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActiveLocksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActiveLocksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ActiveLockResource) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveLockResource) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveLockResource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.UnlockDate) > 0 {
		i -= len(m.UnlockDate)
		copy(dAtA[i:], m.UnlockDate)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UnlockDate)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTotalLockedAmountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalLockedAmountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalLockedAmountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTotalLockedAmountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalLockedAmountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalLockedAmountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TotalLocked.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLocksForAddressesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLocksForAddressesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLocksForAddressesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Addresses) > 0 {
		i -= len(m.Addresses)
		copy(dAtA[i:], m.Addresses)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Addresses)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLocksForAddressesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLocksForAddressesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLocksForAddressesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AccountLocksResource) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountLocksResource) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountLocksResource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LockResource) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LockResource) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LockResource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.UnlockDate) > 0 {
		i -= len(m.UnlockDate)
		copy(dAtA[i:], m.UnlockDate)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UnlockDate)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLocksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLocksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLocksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLocksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLocksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLocksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryActiveLocksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryActiveLocksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *ActiveLockResource) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.UnlockDate)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTotalLockedAmountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTotalLockedAmountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalLocked.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLocksForAddressesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addresses)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLocksForAddressesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *AccountLocksResource) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *LockResource) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UnlockDate)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLocksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLocksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryActiveLocksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActiveLocksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActiveLocksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActiveLocksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActiveLocksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActiveLocksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, ActiveLockResource{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActiveLockResource) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveLockResource: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveLockResource: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnlockDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalLockedAmountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalLockedAmountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalLockedAmountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalLockedAmountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalLockedAmountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalLockedAmountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLocked", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalLocked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLocksForAddressesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLocksForAddressesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLocksForAddressesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLocksForAddressesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLocksForAddressesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLocksForAddressesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, AccountLocksResource{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountLocksResource) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountLocksResource: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountLocksResource: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, LockResource{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LockResource) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LockResource: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LockResource: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnlockDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLocksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLocksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLocksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLocksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLocksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLocksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, LockResource{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
