// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optio/lockup/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgLock struct {
	LockupAddress string  `protobuf:"bytes,1,opt,name=lockupAddress,proto3" json:"lockupAddress,omitempty"`
	Locks         []*Lock `protobuf:"bytes,2,rep,name=locks,proto3" json:"locks,omitempty"`
}

func (m *MsgLock) Reset()         { *m = MsgLock{} }
func (m *MsgLock) String() string { return proto.CompactTextString(m) }
func (*MsgLock) ProtoMessage()    {}
func (*MsgLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{0}
}
func (m *MsgLock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLock.Merge(m, src)
}
func (m *MsgLock) XXX_Size() int {
	return m.Size()
}
func (m *MsgLock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLock proto.InternalMessageInfo

func (m *MsgLock) GetLockupAddress() string {
	if m != nil {
		return m.LockupAddress
	}
	return ""
}

func (m *MsgLock) GetLocks() []*Lock {
	if m != nil {
		return m.Locks
	}
	return nil
}

type MsgLockResponse struct {
}

func (m *MsgLockResponse) Reset()         { *m = MsgLockResponse{} }
func (m *MsgLockResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLockResponse) ProtoMessage()    {}
func (*MsgLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{1}
}
func (m *MsgLockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockResponse.Merge(m, src)
}
func (m *MsgLockResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockResponse proto.InternalMessageInfo

type MsgExtend struct {
	ExtendingAddress string       `protobuf:"bytes,1,opt,name=extendingAddress,proto3" json:"extendingAddress,omitempty"`
	Extensions       []*Extension `protobuf:"bytes,2,rep,name=extensions,proto3" json:"extensions,omitempty"`
}

func (m *MsgExtend) Reset()         { *m = MsgExtend{} }
func (m *MsgExtend) String() string { return proto.CompactTextString(m) }
func (*MsgExtend) ProtoMessage()    {}
func (*MsgExtend) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{2}
}
func (m *MsgExtend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExtend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExtend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExtend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExtend.Merge(m, src)
}
func (m *MsgExtend) XXX_Size() int {
	return m.Size()
}
func (m *MsgExtend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExtend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExtend proto.InternalMessageInfo

func (m *MsgExtend) GetExtendingAddress() string {
	if m != nil {
		return m.ExtendingAddress
	}
	return ""
}

func (m *MsgExtend) GetExtensions() []*Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type MsgExtendResponse struct {
}

func (m *MsgExtendResponse) Reset()         { *m = MsgExtendResponse{} }
func (m *MsgExtendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExtendResponse) ProtoMessage()    {}
func (*MsgExtendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{3}
}
func (m *MsgExtendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExtendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExtendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExtendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExtendResponse.Merge(m, src)
}
func (m *MsgExtendResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExtendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExtendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExtendResponse proto.InternalMessageInfo

type MsgSendDelegateAndLock struct {
	FromAddress string `protobuf:"bytes,1,opt,name=fromAddress,proto3" json:"fromAddress,omitempty"`
	ToAddress   string `protobuf:"bytes,2,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	ValAddress  string `protobuf:"bytes,3,opt,name=valAddress,proto3" json:"valAddress,omitempty"`
	Amount      string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	UnlockDate  string `protobuf:"bytes,5,opt,name=unlockDate,proto3" json:"unlockDate,omitempty"`
}

func (m *MsgSendDelegateAndLock) Reset()         { *m = MsgSendDelegateAndLock{} }
func (m *MsgSendDelegateAndLock) String() string { return proto.CompactTextString(m) }
func (*MsgSendDelegateAndLock) ProtoMessage()    {}
func (*MsgSendDelegateAndLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{4}
}
func (m *MsgSendDelegateAndLock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendDelegateAndLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendDelegateAndLock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendDelegateAndLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendDelegateAndLock.Merge(m, src)
}
func (m *MsgSendDelegateAndLock) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendDelegateAndLock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendDelegateAndLock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendDelegateAndLock proto.InternalMessageInfo

func (m *MsgSendDelegateAndLock) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgSendDelegateAndLock) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MsgSendDelegateAndLock) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

func (m *MsgSendDelegateAndLock) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgSendDelegateAndLock) GetUnlockDate() string {
	if m != nil {
		return m.UnlockDate
	}
	return ""
}

type MsgSendDelegateAndLockResponse struct {
}

func (m *MsgSendDelegateAndLockResponse) Reset()         { *m = MsgSendDelegateAndLockResponse{} }
func (m *MsgSendDelegateAndLockResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendDelegateAndLockResponse) ProtoMessage()    {}
func (*MsgSendDelegateAndLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{5}
}
func (m *MsgSendDelegateAndLockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendDelegateAndLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendDelegateAndLockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendDelegateAndLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendDelegateAndLockResponse.Merge(m, src)
}
func (m *MsgSendDelegateAndLockResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendDelegateAndLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendDelegateAndLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendDelegateAndLockResponse proto.InternalMessageInfo

type MsgMultiSendDelegateAndLock struct {
	FromAddress string    `protobuf:"bytes,1,opt,name=fromAddress,proto3" json:"fromAddress,omitempty"`
	TotalAmount string    `protobuf:"bytes,2,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Outputs     []*Output `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (m *MsgMultiSendDelegateAndLock) Reset()         { *m = MsgMultiSendDelegateAndLock{} }
func (m *MsgMultiSendDelegateAndLock) String() string { return proto.CompactTextString(m) }
func (*MsgMultiSendDelegateAndLock) ProtoMessage()    {}
func (*MsgMultiSendDelegateAndLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{6}
}
func (m *MsgMultiSendDelegateAndLock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMultiSendDelegateAndLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMultiSendDelegateAndLock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMultiSendDelegateAndLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMultiSendDelegateAndLock.Merge(m, src)
}
func (m *MsgMultiSendDelegateAndLock) XXX_Size() int {
	return m.Size()
}
func (m *MsgMultiSendDelegateAndLock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMultiSendDelegateAndLock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMultiSendDelegateAndLock proto.InternalMessageInfo

func (m *MsgMultiSendDelegateAndLock) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgMultiSendDelegateAndLock) GetTotalAmount() string {
	if m != nil {
		return m.TotalAmount
	}
	return ""
}

func (m *MsgMultiSendDelegateAndLock) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type MsgMultiSendDelegateAndLockResponse struct {
}

func (m *MsgMultiSendDelegateAndLockResponse) Reset()         { *m = MsgMultiSendDelegateAndLockResponse{} }
func (m *MsgMultiSendDelegateAndLockResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMultiSendDelegateAndLockResponse) ProtoMessage()    {}
func (*MsgMultiSendDelegateAndLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{7}
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMultiSendDelegateAndLockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMultiSendDelegateAndLockResponse.Merge(m, src)
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMultiSendDelegateAndLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMultiSendDelegateAndLockResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgLock)(nil), "optio.lockup.MsgLock")
	proto.RegisterType((*MsgLockResponse)(nil), "optio.lockup.MsgLockResponse")
	proto.RegisterType((*MsgExtend)(nil), "optio.lockup.MsgExtend")
	proto.RegisterType((*MsgExtendResponse)(nil), "optio.lockup.MsgExtendResponse")
	proto.RegisterType((*MsgSendDelegateAndLock)(nil), "optio.lockup.MsgSendDelegateAndLock")
	proto.RegisterType((*MsgSendDelegateAndLockResponse)(nil), "optio.lockup.MsgSendDelegateAndLockResponse")
	proto.RegisterType((*MsgMultiSendDelegateAndLock)(nil), "optio.lockup.MsgMultiSendDelegateAndLock")
	proto.RegisterType((*MsgMultiSendDelegateAndLockResponse)(nil), "optio.lockup.MsgMultiSendDelegateAndLockResponse")
}

func init() { proto.RegisterFile("optio/lockup/tx.proto", fileDescriptor_6000163095da8e34) }

var fileDescriptor_6000163095da8e34 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x97, 0x76, 0xed, 0xd4, 0xaf, 0x20, 0x56, 0x6f, 0x5d, 0x4b, 0x18, 0xa1, 0x2a, 0x43,
	0x2a, 0xd5, 0x94, 0xa8, 0xe3, 0x80, 0x54, 0x71, 0xe9, 0xb4, 0x71, 0x22, 0x4c, 0x2a, 0x37, 0x2e,
	0x28, 0x4d, 0x4c, 0x88, 0xda, 0xc4, 0x51, 0xed, 0x94, 0x72, 0x43, 0x5c, 0xb8, 0xf2, 0x0e, 0xbc,
	0xc0, 0x9e, 0x81, 0x13, 0xc7, 0x1d, 0x39, 0xa2, 0xf6, 0xb0, 0x07, 0xe0, 0x05, 0x90, 0xe3, 0x24,
	0x8b, 0xd5, 0x16, 0x4d, 0x5c, 0x9a, 0xfa, 0xff, 0xfb, 0xfc, 0xf9, 0xff, 0xb7, 0x2d, 0x43, 0x9d,
	0x84, 0xcc, 0x23, 0xc6, 0x84, 0xd8, 0xe3, 0x28, 0x34, 0xd8, 0x5c, 0x0f, 0xa7, 0x84, 0x11, 0x74,
	0x27, 0x96, 0x75, 0x21, 0xab, 0x35, 0xcb, 0xf7, 0x02, 0x62, 0xc4, 0xbf, 0xa2, 0x40, 0x6d, 0xd8,
	0x84, 0xfa, 0x84, 0x1a, 0x3e, 0x75, 0x8d, 0x59, 0x8f, 0x7f, 0x12, 0xa0, 0x25, 0x60, 0x64, 0x51,
	0x6c, 0xcc, 0x7a, 0x23, 0xcc, 0xac, 0x9e, 0x61, 0x13, 0x2f, 0x48, 0xf8, 0x7d, 0xc1, 0xdf, 0xc5,
	0x23, 0x43, 0x0c, 0x12, 0xb4, 0xef, 0x12, 0x97, 0x08, 0x9d, 0xff, 0x4b, 0x54, 0x55, 0x72, 0x68,
	0xd9, 0x36, 0x89, 0x02, 0x96, 0xba, 0x90, 0x18, 0xff, 0x24, 0xe0, 0x50, 0x02, 0x78, 0xce, 0x70,
	0x40, 0x3d, 0x92, 0x79, 0x90, 0x28, 0x89, 0x58, 0x18, 0x25, 0x1d, 0xdb, 0x3e, 0xec, 0x98, 0xd4,
	0x7d, 0x45, 0xec, 0x31, 0x3a, 0x82, 0xbb, 0xa2, 0x62, 0xe0, 0x38, 0x53, 0x4c, 0x69, 0x53, 0x69,
	0x29, 0x9d, 0xca, 0x50, 0x16, 0x51, 0x07, 0x4a, 0x5c, 0xa0, 0xcd, 0x42, 0xab, 0xd8, 0xa9, 0x9e,
	0x20, 0x3d, 0xbf, 0x73, 0x3a, 0x6f, 0x34, 0x14, 0x05, 0x7d, 0xf4, 0xe5, 0xfa, 0xb2, 0x2b, 0xcf,
	0x6e, 0xd7, 0xe0, 0x5e, 0xb2, 0xdc, 0x10, 0xd3, 0x90, 0x04, 0x14, 0xb7, 0xbf, 0x2a, 0x50, 0x31,
	0xa9, 0x7b, 0xce, 0x3d, 0x3b, 0xa8, 0x0b, 0xbb, 0xb1, 0x7b, 0xc7, 0x0b, 0x5c, 0xd9, 0xc7, 0x8a,
	0x8e, 0x9e, 0x03, 0x64, 0x49, 0x53, 0x3f, 0x0d, 0xd9, 0xcf, 0x79, 0xca, 0x87, 0xb9, 0xd2, 0x7e,
	0x9d, 0x3b, 0x5b, 0xe9, 0xd7, 0xde, 0x83, 0x5a, 0x66, 0x24, 0xb3, 0xf7, 0x43, 0x81, 0x03, 0x93,
	0xba, 0x6f, 0x70, 0xe0, 0x9c, 0xe1, 0x09, 0x76, 0x2d, 0x86, 0x07, 0x81, 0x13, 0x6f, 0x58, 0x0b,
	0xaa, 0xef, 0xa7, 0xc4, 0x97, 0x6d, 0xe6, 0x25, 0x74, 0x08, 0x15, 0x46, 0x52, 0x5e, 0x88, 0xf9,
	0x8d, 0x80, 0x34, 0x80, 0x99, 0x35, 0x49, 0x71, 0x31, 0xc6, 0x39, 0x05, 0x1d, 0x40, 0xd9, 0xf2,
	0xf9, 0xe9, 0x37, 0xb7, 0x63, 0x96, 0x8c, 0xf8, 0xbc, 0x28, 0xe0, 0x01, 0xcf, 0x2c, 0x86, 0x9b,
	0x25, 0x31, 0xef, 0x46, 0xe9, 0xef, 0xf2, 0x78, 0x79, 0x1f, 0xed, 0x16, 0x68, 0xeb, 0x33, 0x64,
	0x31, 0xbf, 0x2b, 0xf0, 0xc0, 0xa4, 0xae, 0x19, 0x4d, 0x98, 0xf7, 0x7f, 0x59, 0x5b, 0x50, 0x65,
	0x84, 0x59, 0x93, 0x81, 0xb0, 0x2c, 0xd2, 0xe6, 0x25, 0xa4, 0xc3, 0x8e, 0xb8, 0x7b, 0x3c, 0x2c,
	0x3f, 0xac, 0x7d, 0xf9, 0xb0, 0x2e, 0x62, 0x38, 0x4c, 0x8b, 0xd6, 0xe4, 0x78, 0x02, 0x8f, 0xff,
	0x61, 0x32, 0x0d, 0x73, 0xf2, 0xa7, 0x00, 0x45, 0x93, 0xba, 0xe8, 0x05, 0x6c, 0xc7, 0xe6, 0xeb,
	0xf2, 0x3a, 0xc9, 0x0d, 0x54, 0x1f, 0xae, 0x95, 0xd3, 0x2e, 0xe8, 0x14, 0xca, 0xc9, 0xa5, 0x6c,
	0xac, 0x14, 0x0a, 0xa0, 0x3e, 0xda, 0x00, 0xb2, 0x1e, 0x1e, 0xec, 0xad, 0xdb, 0xcd, 0xa3, 0x95,
	0x79, 0x6b, 0xaa, 0xd4, 0xe3, 0xdb, 0x54, 0x65, 0x4b, 0xcd, 0xa1, 0xb9, 0xf1, 0xf4, 0x9e, 0xae,
	0x74, 0xda, 0x54, 0xaa, 0xf6, 0x6e, 0x5d, 0x9a, 0xae, 0xac, 0x96, 0x3e, 0x5f, 0x5f, 0x76, 0x95,
	0xd3, 0x97, 0x3f, 0x17, 0x9a, 0x72, 0xb5, 0xd0, 0x94, 0xdf, 0x0b, 0x4d, 0xf9, 0xb6, 0xd4, 0xb6,
	0xae, 0x96, 0xda, 0xd6, 0xaf, 0xa5, 0xb6, 0xf5, 0xf6, 0xd8, 0xf5, 0xd8, 0x87, 0x68, 0xa4, 0xdb,
	0xc4, 0x37, 0x2e, 0x78, 0xf7, 0xd7, 0x98, 0x7d, 0x24, 0xd3, 0xb1, 0x21, 0xde, 0xa5, 0x79, 0xf6,
	0x1c, 0x7f, 0x0a, 0x31, 0x1d, 0x95, 0xe3, 0x97, 0xe9, 0xd9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3c, 0xd9, 0x93, 0xc6, 0xab, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Lock(ctx context.Context, in *MsgLock, opts ...grpc.CallOption) (*MsgLockResponse, error)
	Extend(ctx context.Context, in *MsgExtend, opts ...grpc.CallOption) (*MsgExtendResponse, error)
	SendDelegateAndLock(ctx context.Context, in *MsgSendDelegateAndLock, opts ...grpc.CallOption) (*MsgSendDelegateAndLockResponse, error)
	MultiSendDelegateAndLock(ctx context.Context, in *MsgMultiSendDelegateAndLock, opts ...grpc.CallOption) (*MsgMultiSendDelegateAndLockResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Lock(ctx context.Context, in *MsgLock, opts ...grpc.CallOption) (*MsgLockResponse, error) {
	out := new(MsgLockResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Msg/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Extend(ctx context.Context, in *MsgExtend, opts ...grpc.CallOption) (*MsgExtendResponse, error) {
	out := new(MsgExtendResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Msg/Extend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendDelegateAndLock(ctx context.Context, in *MsgSendDelegateAndLock, opts ...grpc.CallOption) (*MsgSendDelegateAndLockResponse, error) {
	out := new(MsgSendDelegateAndLockResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Msg/SendDelegateAndLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MultiSendDelegateAndLock(ctx context.Context, in *MsgMultiSendDelegateAndLock, opts ...grpc.CallOption) (*MsgMultiSendDelegateAndLockResponse, error) {
	out := new(MsgMultiSendDelegateAndLockResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Msg/MultiSendDelegateAndLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Lock(context.Context, *MsgLock) (*MsgLockResponse, error)
	Extend(context.Context, *MsgExtend) (*MsgExtendResponse, error)
	SendDelegateAndLock(context.Context, *MsgSendDelegateAndLock) (*MsgSendDelegateAndLockResponse, error)
	MultiSendDelegateAndLock(context.Context, *MsgMultiSendDelegateAndLock) (*MsgMultiSendDelegateAndLockResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Lock(ctx context.Context, req *MsgLock) (*MsgLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedMsgServer) Extend(ctx context.Context, req *MsgExtend) (*MsgExtendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Extend not implemented")
}
func (*UnimplementedMsgServer) SendDelegateAndLock(ctx context.Context, req *MsgSendDelegateAndLock) (*MsgSendDelegateAndLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDelegateAndLock not implemented")
}
func (*UnimplementedMsgServer) MultiSendDelegateAndLock(ctx context.Context, req *MsgMultiSendDelegateAndLock) (*MsgMultiSendDelegateAndLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiSendDelegateAndLock not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Msg/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Lock(ctx, req.(*MsgLock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Extend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExtend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Extend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Msg/Extend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Extend(ctx, req.(*MsgExtend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendDelegateAndLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendDelegateAndLock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendDelegateAndLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Msg/SendDelegateAndLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendDelegateAndLock(ctx, req.(*MsgSendDelegateAndLock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MultiSendDelegateAndLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMultiSendDelegateAndLock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MultiSendDelegateAndLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Msg/MultiSendDelegateAndLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MultiSendDelegateAndLock(ctx, req.(*MsgMultiSendDelegateAndLock))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "optio.lockup.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _Msg_Lock_Handler,
		},
		{
			MethodName: "Extend",
			Handler:    _Msg_Extend_Handler,
		},
		{
			MethodName: "SendDelegateAndLock",
			Handler:    _Msg_SendDelegateAndLock_Handler,
		},
		{
			MethodName: "MultiSendDelegateAndLock",
			Handler:    _Msg_MultiSendDelegateAndLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optio/lockup/tx.proto",
}

func (m *MsgLock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.LockupAddress) > 0 {
		i -= len(m.LockupAddress)
		copy(dAtA[i:], m.LockupAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LockupAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgExtend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExtend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExtend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Extensions) > 0 {
		for iNdEx := len(m.Extensions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Extensions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ExtendingAddress) > 0 {
		i -= len(m.ExtendingAddress)
		copy(dAtA[i:], m.ExtendingAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ExtendingAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExtendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExtendResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExtendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSendDelegateAndLock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendDelegateAndLock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendDelegateAndLock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UnlockDate) > 0 {
		i -= len(m.UnlockDate)
		copy(dAtA[i:], m.UnlockDate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UnlockDate)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendDelegateAndLockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendDelegateAndLockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendDelegateAndLockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMultiSendDelegateAndLock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMultiSendDelegateAndLock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMultiSendDelegateAndLock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Outputs) > 0 {
		for iNdEx := len(m.Outputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Outputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TotalAmount) > 0 {
		i -= len(m.TotalAmount)
		copy(dAtA[i:], m.TotalAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TotalAmount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMultiSendDelegateAndLockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMultiSendDelegateAndLockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMultiSendDelegateAndLockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LockupAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgLockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgExtend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ExtendingAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Extensions) > 0 {
		for _, e := range m.Extensions {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgExtendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSendDelegateAndLock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UnlockDate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendDelegateAndLockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMultiSendDelegateAndLock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TotalAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Outputs) > 0 {
		for _, e := range m.Outputs {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgMultiSendDelegateAndLockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockupAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockupAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, &Lock{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExtend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExtend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExtend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtendingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extensions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extensions = append(m.Extensions, &Extension{})
			if err := m.Extensions[len(m.Extensions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExtendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExtendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExtendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendDelegateAndLock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendDelegateAndLock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendDelegateAndLock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnlockDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendDelegateAndLockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendDelegateAndLockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendDelegateAndLockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMultiSendDelegateAndLock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMultiSendDelegateAndLock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMultiSendDelegateAndLock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Outputs = append(m.Outputs, &Output{})
			if err := m.Outputs[len(m.Outputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMultiSendDelegateAndLockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMultiSendDelegateAndLockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMultiSendDelegateAndLockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
