// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optio/lockup/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgLock struct {
	Address    string                `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	UnlockDate string                `protobuf:"bytes,2,opt,name=unlock_date,json=unlockDate,proto3" json:"unlock_date,omitempty"`
	Amount     cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *MsgLock) Reset()         { *m = MsgLock{} }
func (m *MsgLock) String() string { return proto.CompactTextString(m) }
func (*MsgLock) ProtoMessage()    {}
func (*MsgLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{0}
}
func (m *MsgLock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLock.Merge(m, src)
}
func (m *MsgLock) XXX_Size() int {
	return m.Size()
}
func (m *MsgLock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLock proto.InternalMessageInfo

func (m *MsgLock) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgLock) GetUnlockDate() string {
	if m != nil {
		return m.UnlockDate
	}
	return ""
}

type MsgLockResponse struct {
}

func (m *MsgLockResponse) Reset()         { *m = MsgLockResponse{} }
func (m *MsgLockResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLockResponse) ProtoMessage()    {}
func (*MsgLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{1}
}
func (m *MsgLockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockResponse.Merge(m, src)
}
func (m *MsgLockResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockResponse proto.InternalMessageInfo

type MsgExtend struct {
	Address    string       `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Extensions []*Extension `protobuf:"bytes,2,rep,name=extensions,proto3" json:"extensions,omitempty"`
}

func (m *MsgExtend) Reset()         { *m = MsgExtend{} }
func (m *MsgExtend) String() string { return proto.CompactTextString(m) }
func (*MsgExtend) ProtoMessage()    {}
func (*MsgExtend) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{2}
}
func (m *MsgExtend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExtend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExtend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExtend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExtend.Merge(m, src)
}
func (m *MsgExtend) XXX_Size() int {
	return m.Size()
}
func (m *MsgExtend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExtend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExtend proto.InternalMessageInfo

func (m *MsgExtend) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgExtend) GetExtensions() []*Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type MsgExtendResponse struct {
}

func (m *MsgExtendResponse) Reset()         { *m = MsgExtendResponse{} }
func (m *MsgExtendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExtendResponse) ProtoMessage()    {}
func (*MsgExtendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{3}
}
func (m *MsgExtendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExtendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExtendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExtendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExtendResponse.Merge(m, src)
}
func (m *MsgExtendResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExtendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExtendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExtendResponse proto.InternalMessageInfo

type MsgSendDelegateAndLock struct {
	FromAddress      string                `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress        string                `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	ValidatorAddress string                `protobuf:"bytes,3,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	UnlockDate       string                `protobuf:"bytes,4,opt,name=unlock_date,json=unlockDate,proto3" json:"unlock_date,omitempty"`
	Amount           cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *MsgSendDelegateAndLock) Reset()         { *m = MsgSendDelegateAndLock{} }
func (m *MsgSendDelegateAndLock) String() string { return proto.CompactTextString(m) }
func (*MsgSendDelegateAndLock) ProtoMessage()    {}
func (*MsgSendDelegateAndLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{4}
}
func (m *MsgSendDelegateAndLock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendDelegateAndLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendDelegateAndLock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendDelegateAndLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendDelegateAndLock.Merge(m, src)
}
func (m *MsgSendDelegateAndLock) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendDelegateAndLock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendDelegateAndLock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendDelegateAndLock proto.InternalMessageInfo

func (m *MsgSendDelegateAndLock) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgSendDelegateAndLock) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MsgSendDelegateAndLock) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *MsgSendDelegateAndLock) GetUnlockDate() string {
	if m != nil {
		return m.UnlockDate
	}
	return ""
}

type MsgSendDelegateAndLockResponse struct {
}

func (m *MsgSendDelegateAndLockResponse) Reset()         { *m = MsgSendDelegateAndLockResponse{} }
func (m *MsgSendDelegateAndLockResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendDelegateAndLockResponse) ProtoMessage()    {}
func (*MsgSendDelegateAndLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{5}
}
func (m *MsgSendDelegateAndLockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendDelegateAndLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendDelegateAndLockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendDelegateAndLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendDelegateAndLockResponse.Merge(m, src)
}
func (m *MsgSendDelegateAndLockResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendDelegateAndLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendDelegateAndLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendDelegateAndLockResponse proto.InternalMessageInfo

type MsgMultiSendDelegateAndLock struct {
	FromAddress string                            `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Input       cosmossdk_io_math.Int             `protobuf:"bytes,2,opt,name=input,proto3,customtype=cosmossdk.io/math.Int" json:"input"`
	Outputs     []*MultiSendDelegateAndLockOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (m *MsgMultiSendDelegateAndLock) Reset()         { *m = MsgMultiSendDelegateAndLock{} }
func (m *MsgMultiSendDelegateAndLock) String() string { return proto.CompactTextString(m) }
func (*MsgMultiSendDelegateAndLock) ProtoMessage()    {}
func (*MsgMultiSendDelegateAndLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{6}
}
func (m *MsgMultiSendDelegateAndLock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMultiSendDelegateAndLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMultiSendDelegateAndLock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMultiSendDelegateAndLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMultiSendDelegateAndLock.Merge(m, src)
}
func (m *MsgMultiSendDelegateAndLock) XXX_Size() int {
	return m.Size()
}
func (m *MsgMultiSendDelegateAndLock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMultiSendDelegateAndLock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMultiSendDelegateAndLock proto.InternalMessageInfo

func (m *MsgMultiSendDelegateAndLock) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgMultiSendDelegateAndLock) GetOutputs() []*MultiSendDelegateAndLockOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type MsgMultiSendDelegateAndLockResponse struct {
}

func (m *MsgMultiSendDelegateAndLockResponse) Reset()         { *m = MsgMultiSendDelegateAndLockResponse{} }
func (m *MsgMultiSendDelegateAndLockResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMultiSendDelegateAndLockResponse) ProtoMessage()    {}
func (*MsgMultiSendDelegateAndLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6000163095da8e34, []int{7}
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMultiSendDelegateAndLockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMultiSendDelegateAndLockResponse.Merge(m, src)
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMultiSendDelegateAndLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMultiSendDelegateAndLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMultiSendDelegateAndLockResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgLock)(nil), "optio.lockup.MsgLock")
	proto.RegisterType((*MsgLockResponse)(nil), "optio.lockup.MsgLockResponse")
	proto.RegisterType((*MsgExtend)(nil), "optio.lockup.MsgExtend")
	proto.RegisterType((*MsgExtendResponse)(nil), "optio.lockup.MsgExtendResponse")
	proto.RegisterType((*MsgSendDelegateAndLock)(nil), "optio.lockup.MsgSendDelegateAndLock")
	proto.RegisterType((*MsgSendDelegateAndLockResponse)(nil), "optio.lockup.MsgSendDelegateAndLockResponse")
	proto.RegisterType((*MsgMultiSendDelegateAndLock)(nil), "optio.lockup.MsgMultiSendDelegateAndLock")
	proto.RegisterType((*MsgMultiSendDelegateAndLockResponse)(nil), "optio.lockup.MsgMultiSendDelegateAndLockResponse")
}

func init() { proto.RegisterFile("optio/lockup/tx.proto", fileDescriptor_6000163095da8e34) }

var fileDescriptor_6000163095da8e34 = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x8e, 0xd2, 0x5c,
	0x14, 0xa6, 0x30, 0x40, 0x38, 0x90, 0xfc, 0x3f, 0x1d, 0x91, 0x5a, 0x9d, 0x82, 0xa8, 0xc9, 0x38,
	0x62, 0x2b, 0xe3, 0xc2, 0xc4, 0xb8, 0x81, 0xcc, 0x10, 0x27, 0xb1, 0x4e, 0x52, 0x77, 0x6e, 0x48,
	0xa1, 0xd7, 0x4e, 0x03, 0xed, 0x6d, 0xb8, 0xb7, 0x88, 0x3b, 0x63, 0xe2, 0xde, 0x07, 0xf0, 0x01,
	0x5c, 0xce, 0xc2, 0x87, 0x98, 0xe5, 0xc4, 0x95, 0x71, 0x31, 0x31, 0xb0, 0x98, 0x07, 0xf0, 0x05,
	0x4c, 0x7b, 0xdb, 0x66, 0x18, 0x0a, 0x99, 0x8c, 0x1b, 0xe8, 0x3d, 0xdf, 0x77, 0xce, 0xfd, 0xce,
	0x77, 0x4e, 0x2e, 0x54, 0xb0, 0x4b, 0x2d, 0xac, 0x8c, 0xf0, 0x60, 0xe8, 0xb9, 0x0a, 0x9d, 0xca,
	0xee, 0x18, 0x53, 0xcc, 0x97, 0x82, 0xb0, 0xcc, 0xc2, 0x62, 0x59, 0xb7, 0x2d, 0x07, 0x2b, 0xc1,
	0x2f, 0x23, 0x88, 0xd5, 0x01, 0x26, 0x36, 0x26, 0x8a, 0x4d, 0x4c, 0x65, 0xd2, 0xf2, 0xff, 0x42,
	0x40, 0x0a, 0x81, 0xbe, 0x4e, 0x90, 0x32, 0x69, 0xf5, 0x11, 0xd5, 0x5b, 0xca, 0x00, 0x5b, 0x4e,
	0x88, 0xdf, 0x62, 0x78, 0x2f, 0x38, 0x29, 0xec, 0x10, 0x42, 0x37, 0x4c, 0x6c, 0x62, 0x16, 0xf7,
	0xbf, 0xc2, 0xe8, 0x9d, 0x05, 0x85, 0x68, 0x4a, 0x91, 0x43, 0x2c, 0x1c, 0x97, 0x5b, 0x40, 0xb1,
	0x47, 0x5d, 0x8f, 0x32, 0xa8, 0xf1, 0x95, 0x83, 0xbc, 0x4a, 0xcc, 0x57, 0x78, 0x30, 0xe4, 0x05,
	0xc8, 0xeb, 0x86, 0x31, 0x46, 0x84, 0x08, 0x5c, 0x9d, 0xdb, 0x2e, 0x68, 0xd1, 0x91, 0xaf, 0x41,
	0xd1, 0x73, 0xfc, 0xf4, 0x9e, 0xa1, 0x53, 0x24, 0xa4, 0x03, 0x14, 0x58, 0x68, 0x4f, 0xa7, 0x88,
	0x7f, 0x09, 0x39, 0xdd, 0xc6, 0x9e, 0x43, 0x85, 0x8c, 0x8f, 0x75, 0x9e, 0x9c, 0x9c, 0xd5, 0x52,
	0xbf, 0xce, 0x6a, 0x15, 0xa6, 0x9d, 0x18, 0x43, 0xd9, 0xc2, 0x8a, 0xad, 0xd3, 0x23, 0xf9, 0xc0,
	0xa1, 0x3f, 0xbe, 0x3f, 0x86, 0xb0, 0xa9, 0x03, 0x87, 0x7e, 0x3b, 0x3f, 0xde, 0xe1, 0xb4, 0x30,
	0xff, 0x79, 0xe9, 0xd3, 0xf9, 0xf1, 0x4e, 0x74, 0x71, 0xa3, 0x0c, 0xff, 0x85, 0xea, 0x34, 0x44,
	0x5c, 0xec, 0x10, 0xd4, 0x18, 0x41, 0x41, 0x25, 0xe6, 0xbe, 0xdf, 0xa2, 0xb1, 0x46, 0xf2, 0x33,
	0x80, 0xd8, 0x06, 0x22, 0xa4, 0xeb, 0x99, 0xed, 0xe2, 0x6e, 0x55, 0xbe, 0x38, 0x31, 0x79, 0x3f,
	0xc2, 0xb5, 0x0b, 0xd4, 0x4b, 0x02, 0x36, 0xa1, 0x1c, 0xdf, 0x16, 0x4b, 0xf8, 0x9c, 0x86, 0x9b,
	0x2a, 0x31, 0xdf, 0x20, 0xc7, 0xd8, 0x43, 0x23, 0x64, 0xea, 0x14, 0xb5, 0x1d, 0x23, 0xf0, 0xf0,
	0x2e, 0x94, 0xde, 0x8d, 0xb1, 0xdd, 0x5b, 0x54, 0x55, 0xf4, 0x63, 0xed, 0x50, 0xd9, 0x16, 0x00,
	0xc5, 0x31, 0x81, 0x79, 0x59, 0xa0, 0x38, 0x82, 0x1f, 0x41, 0x79, 0xa2, 0x8f, 0x2c, 0x43, 0xa7,
	0x78, 0x1c, 0xb3, 0x02, 0x57, 0xb5, 0xff, 0x63, 0xa0, 0x9d, 0x3c, 0x98, 0x8d, 0x35, 0x83, 0xc9,
	0xfe, 0xe3, 0x60, 0xca, 0xbe, 0x2f, 0x0b, 0xcd, 0x35, 0xea, 0x20, 0x25, 0xdb, 0x10, 0x3b, 0x35,
	0xe7, 0xe0, 0xb6, 0x4a, 0x4c, 0xd5, 0x1b, 0x51, 0xeb, 0x9a, 0x76, 0x75, 0x21, 0x6b, 0x39, 0xae,
	0x47, 0x99, 0x53, 0xd7, 0x68, 0x80, 0xa5, 0xf3, 0x5d, 0xc8, 0xb3, 0xcd, 0xf7, 0xdd, 0xf4, 0xb7,
	0xa1, 0xb9, 0xb8, 0x0d, 0xab, 0x34, 0x1e, 0x06, 0x49, 0x5a, 0x94, 0x9c, 0xe4, 0xc3, 0x03, 0xb8,
	0xb7, 0xa6, 0xc9, 0xc8, 0x8c, 0xdd, 0x3f, 0x69, 0xc8, 0xa8, 0xc4, 0xe4, 0x5f, 0xc0, 0x46, 0xd0,
	0x7c, 0xe5, 0x92, 0x00, 0xb6, 0xe8, 0xe2, 0x56, 0x62, 0x38, 0xaa, 0xc2, 0x77, 0x20, 0x17, 0x2e,
	0x7f, 0x75, 0x89, 0xc8, 0x00, 0xb1, 0xb6, 0x02, 0x88, 0x6b, 0x58, 0xb0, 0x99, 0x34, 0x8d, 0xfb,
	0x4b, 0x79, 0x09, 0x2c, 0xb1, 0x79, 0x15, 0x56, 0x7c, 0xd5, 0x14, 0x84, 0x95, 0xd3, 0x7f, 0xb8,
	0x54, 0x69, 0x15, 0x55, 0x6c, 0x5d, 0x99, 0x1a, 0xdd, 0x2c, 0x66, 0x3f, 0xfa, 0xe3, 0xef, 0x74,
	0x4f, 0x66, 0x12, 0x77, 0x3a, 0x93, 0xb8, 0xdf, 0x33, 0x89, 0xfb, 0x32, 0x97, 0x52, 0xa7, 0x73,
	0x29, 0xf5, 0x73, 0x2e, 0xa5, 0xde, 0x36, 0x4d, 0x8b, 0x1e, 0x79, 0x7d, 0x79, 0x80, 0x6d, 0xe5,
	0xd0, 0xaf, 0xfe, 0x1a, 0xd1, 0xf7, 0x78, 0x3c, 0x54, 0xd8, 0x73, 0x39, 0x8d, 0x1f, 0xfc, 0x0f,
	0x2e, 0x22, 0xfd, 0x5c, 0xf0, 0x60, 0x3e, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x23, 0x12,
	0x84, 0x0d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Lock locks tokens for a specific address.
	Lock(ctx context.Context, in *MsgLock, opts ...grpc.CallOption) (*MsgLockResponse, error)
	// Extend extends the lock duration for a specific address.
	Extend(ctx context.Context, in *MsgExtend, opts ...grpc.CallOption) (*MsgExtendResponse, error)
	// SendDelegateAndLock sends tokens to a specific address, delegates them to a validator, and locks them until a specified unlock date.
	SendDelegateAndLock(ctx context.Context, in *MsgSendDelegateAndLock, opts ...grpc.CallOption) (*MsgSendDelegateAndLockResponse, error)
	// MultiSendDelegateAndLock sends tokens to multiple addresses, delegates them to a validator, and locks them until specified unlock dates.
	MultiSendDelegateAndLock(ctx context.Context, in *MsgMultiSendDelegateAndLock, opts ...grpc.CallOption) (*MsgMultiSendDelegateAndLockResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Lock(ctx context.Context, in *MsgLock, opts ...grpc.CallOption) (*MsgLockResponse, error) {
	out := new(MsgLockResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Msg/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Extend(ctx context.Context, in *MsgExtend, opts ...grpc.CallOption) (*MsgExtendResponse, error) {
	out := new(MsgExtendResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Msg/Extend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendDelegateAndLock(ctx context.Context, in *MsgSendDelegateAndLock, opts ...grpc.CallOption) (*MsgSendDelegateAndLockResponse, error) {
	out := new(MsgSendDelegateAndLockResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Msg/SendDelegateAndLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MultiSendDelegateAndLock(ctx context.Context, in *MsgMultiSendDelegateAndLock, opts ...grpc.CallOption) (*MsgMultiSendDelegateAndLockResponse, error) {
	out := new(MsgMultiSendDelegateAndLockResponse)
	err := c.cc.Invoke(ctx, "/optio.lockup.Msg/MultiSendDelegateAndLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Lock locks tokens for a specific address.
	Lock(context.Context, *MsgLock) (*MsgLockResponse, error)
	// Extend extends the lock duration for a specific address.
	Extend(context.Context, *MsgExtend) (*MsgExtendResponse, error)
	// SendDelegateAndLock sends tokens to a specific address, delegates them to a validator, and locks them until a specified unlock date.
	SendDelegateAndLock(context.Context, *MsgSendDelegateAndLock) (*MsgSendDelegateAndLockResponse, error)
	// MultiSendDelegateAndLock sends tokens to multiple addresses, delegates them to a validator, and locks them until specified unlock dates.
	MultiSendDelegateAndLock(context.Context, *MsgMultiSendDelegateAndLock) (*MsgMultiSendDelegateAndLockResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Lock(ctx context.Context, req *MsgLock) (*MsgLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedMsgServer) Extend(ctx context.Context, req *MsgExtend) (*MsgExtendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Extend not implemented")
}
func (*UnimplementedMsgServer) SendDelegateAndLock(ctx context.Context, req *MsgSendDelegateAndLock) (*MsgSendDelegateAndLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDelegateAndLock not implemented")
}
func (*UnimplementedMsgServer) MultiSendDelegateAndLock(ctx context.Context, req *MsgMultiSendDelegateAndLock) (*MsgMultiSendDelegateAndLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiSendDelegateAndLock not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Msg/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Lock(ctx, req.(*MsgLock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Extend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExtend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Extend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Msg/Extend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Extend(ctx, req.(*MsgExtend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendDelegateAndLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendDelegateAndLock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendDelegateAndLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Msg/SendDelegateAndLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendDelegateAndLock(ctx, req.(*MsgSendDelegateAndLock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MultiSendDelegateAndLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMultiSendDelegateAndLock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MultiSendDelegateAndLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.lockup.Msg/MultiSendDelegateAndLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MultiSendDelegateAndLock(ctx, req.(*MsgMultiSendDelegateAndLock))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "optio.lockup.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _Msg_Lock_Handler,
		},
		{
			MethodName: "Extend",
			Handler:    _Msg_Extend_Handler,
		},
		{
			MethodName: "SendDelegateAndLock",
			Handler:    _Msg_SendDelegateAndLock_Handler,
		},
		{
			MethodName: "MultiSendDelegateAndLock",
			Handler:    _Msg_MultiSendDelegateAndLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optio/lockup/tx.proto",
}

func (m *MsgLock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.UnlockDate) > 0 {
		i -= len(m.UnlockDate)
		copy(dAtA[i:], m.UnlockDate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UnlockDate)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgExtend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExtend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExtend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Extensions) > 0 {
		for iNdEx := len(m.Extensions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Extensions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExtendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExtendResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExtendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSendDelegateAndLock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendDelegateAndLock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendDelegateAndLock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.UnlockDate) > 0 {
		i -= len(m.UnlockDate)
		copy(dAtA[i:], m.UnlockDate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UnlockDate)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendDelegateAndLockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendDelegateAndLockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendDelegateAndLockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMultiSendDelegateAndLock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMultiSendDelegateAndLock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMultiSendDelegateAndLock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Outputs) > 0 {
		for iNdEx := len(m.Outputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Outputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size := m.Input.Size()
		i -= size
		if _, err := m.Input.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMultiSendDelegateAndLockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMultiSendDelegateAndLockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMultiSendDelegateAndLockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UnlockDate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgLockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgExtend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Extensions) > 0 {
		for _, e := range m.Extensions {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgExtendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSendDelegateAndLock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UnlockDate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSendDelegateAndLockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMultiSendDelegateAndLock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Input.Size()
	n += 1 + l + sovTx(uint64(l))
	if len(m.Outputs) > 0 {
		for _, e := range m.Outputs {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgMultiSendDelegateAndLockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnlockDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExtend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExtend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExtend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extensions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extensions = append(m.Extensions, &Extension{})
			if err := m.Extensions[len(m.Extensions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExtendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExtendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExtendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendDelegateAndLock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendDelegateAndLock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendDelegateAndLock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnlockDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendDelegateAndLockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendDelegateAndLockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendDelegateAndLockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMultiSendDelegateAndLock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMultiSendDelegateAndLock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMultiSendDelegateAndLock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Input", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Input.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Outputs = append(m.Outputs, &MultiSendDelegateAndLockOutput{})
			if err := m.Outputs[len(m.Outputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMultiSendDelegateAndLockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMultiSendDelegateAndLockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMultiSendDelegateAndLockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
